### ISSUE TITLE
Pink boxes

### ISSUE THREAD

**Issue by ffes** [sky-map-team/stardroid#46] opened 2016-03-01 09:08 UTC
Just upgraded to the 1.8 through Google Play. But I see a **lot** of pink boxes, I assume wrongly rendered names of constellations.

Nexus 5 (original) with Android 6.0.1

I 
![screenshot_20160301-095922](https://cloud.githubusercontent.com/assets/3225656/13422419/fdd552d8-df94-11e5-88ae-11c876d17138.png)

**Comment by jaydeetay** [comment] 2016-03-01 15:08
Thanks for filing the bug report.  The screenshot and phone/Android version are just what we need.

This is a puzzle - I have a Nexus 5 and don't see this.  I'll try to reproduce it in the emulator.

**Comment by ffes** [comment] 2016-03-02 10:11
I am using a Dutch (NL) localized version of Android and therefore the Dutch version of Sky Map. Could it be related to that?

**Comment by jaydeetay** [comment] 2016-03-02 14:10
Thanks Frank.   It gives me an extra thing to try.

**Comment by jaydeetay** [comment] 2016-03-03 21:33
We've now had multiple reports of this from Dutch users on different devices.  Switching my own Nexus 5 to Dutch does not exhibit the problem.  A guess: for some reason the Dutch constellation names include the English names in parenthesis.  Why, I don't know.  I wonder if that just makes them too long or otherwise breaks the rendering.

**Comment by jaydeetay** [comment] 2016-03-05 19:26
Managed to repro on my Nexus 5 (couldn't repro it on the 5x - correction to early comment).  Fixed in 1.9.0.

**Comment by ffes** [comment] 2016-03-09 15:46
Just installed the update from Google Play and indeed it is fixed. Thanks a lot!

**Comment by jaydeetay** [comment] 2016-03-09 15:55
Great to hear!

**Comment by jaydeetay** [comment] 2016-03-10 02:21
It's now happening in Japanese too.  Reopening.
![screenmemo_2016-03-10-08-42-18](https://cloud.githubusercontent.com/assets/16431883/13657382/e8b8124c-e63c-11e5-8822-b26944ad2d83.png)

**Comment by jaydeetay** [comment] 2020-08-27 23:48
Since I haven't seen this in a long time, I'll close it.

**Closed by jaydeetay** 2020-08-27 23:48 UTC
Labels: bug
