### ISSUE TITLE
Crash if gyroscope disabled in app settings

### ISSUE THREAD

**Issue by Blauelf** [sky-map-team/stardroid#406] opened 2021-09-02 15:38 UTC
**Summary:** 

I hoped to get a more steady image if I disable the gyro in the settings. But if I disable the gyroscope and leave the settings, the app immediately crashes. After the loading screen, it crashes again, only way to resume operation is deleting all app data.

**Steps to reproduce:** 

Tick the "Disable gyro" checkbox, leave the menu.

**Expected behavior:** 

Works as it did before.

**Observed behavior:** 

Crashes, will no longer load

**Device and Android version:** 

- Xiaomi Mi 9T Pro (also sold as Redmi K20 Pro)
- MIUI 12.5.2 Global (default ROM)
- Android 11
- Google Play Services 21.30.16

**Screenshots:** 

Not much to see regarding the crash, leave the settings, app closes. So maybe I'll attach some stack trace instead.
[skymap-crash.txt](https://github.com/sky-map-team/stardroid/files/7099325/skymap-crash.txt)

That's from starting after I broke it, I guess the one right after breaking would look similar.

**Comment by jaydeetay** [comment] 2021-09-03 11:54
Thanks a lot for the report! Disable gyro is really a hack for folks whose
phones don't have a gyroscope and switches them back over to the old
compass & accelerometer way of doing things.  Obviously it shouldn't crash
though! So I'll look into that. If you just want to stop the map moving
then tap the manual mode/auto mode button that shows on the main screen
(looks like a finger icon).

**Comment by jaydeetay** [comment] 2021-09-03 11:57
BTW - although I can't reproduce this on my phone, the log you provided is
really useful and I'm pretty sure I can fix the issue based on that.

**Comment by jaydeetay** [comment] 2021-09-05 22:59
Very odd. The smoothing code expects  a sensor event with a value array of size 3. It's not getting one I guess. I think this fix will stop the crash, but it'll basically just turn the smoother into a noop. If the sensor event is the wrong size I'm not sure the app will actually work...but at least it ought not to crash.

**Comment by jaydeetay** [comment] 2021-09-06 14:08
Hmm.  I can now reproduce this on my own phone when I create a new build, but *not* with the app as currently released in the Play Store.  My guess is it's related to upgrading the SDK. I wonder if they deprecated or broke something.

**Comment by marcocipriani01** [comment] 2021-09-06 22:34
On a side note, I've actually experienced the same crash on my Galaxy A50 a few months ago, when I was working on my Telescope.Touch fork. For my app, I solved it by completely removing `ExponentiallyWeightedSmoother`. In my tests, it had no noticeable effect on the sky map - other than sometimes crashing it.

Increasing the refresh rate of the map to 60 FPS had a much better effect, making it extremely smooth and responsive. I achieved it by using `SensorManager.SENSOR_DELAY_FASTEST` in the `SensorOrientationController`, and setting `updatesPerSecond` to `60` in the `Flinger` class. All the mid-range smartphones I tested had no trouble dealing with a 60Hz refresh rate. Maybe give it a try and see if it works for you.

Regards,
Marco Cipriani

**Comment by jaydeetay** [comment] 2021-09-07 12:31
Thanks Marco. Much of Sky Map's code was designed for prehistoric phones -
e.g. the smoother code was the original code built from before most phones
did some kind of sensor fusion.  The refresh rate was also set for "how
high can we set this before the phone locks up"!  Obviously times have
changed.

I'm still a bit puzzled why this happens though - on my own phone it will
crash in the way the OP described if I do a new build against Android-30 so
I wonder if some old API has been disabled.  Ideally I'd keep this code
here as there are still some new phones that lack gyroscopes and don't seem
to properly implement the direction sensor...but perhaps it's time to
retire it.

**Comment by marcocipriani01** [comment] 2021-09-07 14:25
> Much of Sky Map's code was designed for prehistoric phones

Yeah, I spent a lot of time updating Telescope.Touch to use the latest APIs and Android/Java features, especially on the UI side. I also updated some code that handles sensors because of some deprecated API calls. However, it had nothing to do with this issue, and I did it mainly to future-proof my app. I have no idea why the GPlay version works and the debug one doesn't.

> Ideally I'd keep this code here as there are still some new phones that lack gyroscope

I didn't delete the accelerometer code (or anything non-gyroscope related). I only removed the smoother. Feeding the raw values to the map without any smoothing/processing had a slightly positive effect on performance. Removing the accelerometer support would mean removing even modern low-end smartphones from the list of supported devices (e.g. the Galaxy A20 series).

**Comment by jaydeetay** [comment] 2021-09-08 02:49
And rebuilding at the last release (a41fad2) works just fine (though you have to set the version of androidx.core:core-ktx:1.6.0 as I'd inadvertently left the version unspecified). Interesting!

**Comment by jaydeetay** [comment] 2021-09-08 12:16
Here's the diff: https://github.com/sky-map-team/stardroid/compare/1.9.7-RC1...master

The only non-trivial changes are things like dependency versions and build versions.

**Comment by marcocipriani01** [comment] 2021-09-08 13:40
I think it has something to do with the new `targetSdkVersion` and `compileSdkVersion`. I've noticed several times behavior changes when targeting a new Android release. What happens if you revert back to version `30`?

Note that targeting Android 12 (API 31) requires adding the `exported` flag to the launcher activity, otherwise the app may not compile or run: [Manifest merger failed: Apps targeting Android 12](https://stackoverflow.com/a/67412314/6267019)

**Comment by jaydeetay** [comment] 2021-09-12 17:31
Oh silly me. Should have checked this first as it's pretty obvious in hindsight.
It was caused by this well-intentioned PR to upgrade to the latest sensor API:
https://github.com/sky-map-team/stardroid/commit/a884f53db6e60791be6c8822f813b3cad2342227

I haven't looked in detail into why it causes the crash, I'm just going to roll it back for now.  I should have tested it properly before accepting it.

**Comment by jaydeetay** [comment] 2021-09-12 17:32
And the diff I think I should have been looking at was the 'two dot' one: https://github.com/sky-map-team/stardroid/compare/lastworkingversion..master

**Closed** 2021-09-12 17:48 UTC
