### ISSUE TITLE
No Information about the function of the side image buttons

### ISSUE THREAD

**Issue by tusharr-98** [sky-map-team/stardroid#246] opened 2019-03-24 20:58 UTC
**Summary:** 

The user has no idea about the functions of the side image buttons
**Steps to reproduce:** 

Click on the side buttons on the sky map

**Expected behavior:** 

The user should get a nice little toast about the functions of the image button

**Observed behavior:** 

No information provided on clicking the image button 

**Device and Android version:**

Motorola XT1068, Android 6.0, API 23

**Comment by jaydeetay** [comment] 2019-03-24 23:25
I put some comments in the feature request about this. I agree that the SkyMap UI needs work. I'm not sure that firing off a toast every time the button is pressed is the right way to go though.

**Comment by shiv07tiwari** [comment] 2019-03-25 17:23
@jaydeetay @tusharr-98 This is similar to https://github.com/sky-map-team/stardroid/issues/234.
On which work is already going on.

**Comment by jaydeetay** [comment] 2019-03-30 16:25
Yes, I see a number of duplicates of this.  I'm not in favor of the solutions I've seen though.

**Comment by jaydeetay** [comment] 2019-03-30 16:45
Dupe of https://github.com/sky-map-team/stardroid/issues/234

**Closed by jaydeetay** 2019-03-30 16:45 UTC
Labels: enhancement
